fog_detection/urls.py
from django.urls import path 
from . import views
app_name='fog_detection'



urlpatterns = [

    path('',views.home,name='home'),
]

fog_detection_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fog_detection.urls')),
]

fog_detection/models.py
from django.db import models

# Create your models here.

fog_detection/views.py
from django.shortcuts import render
import cv2
import numpy as np
from django.core.files.storage import FileSystemStorage
import os
from django.core.mail import send_mail
from keras.models import load_model





# Create your views here...
def home(request):
    if request.method=="POST" and 'video_file' in request.FILES:
        videofile =request.FILES['video_file']
        file_storage=FileSystemStorage()
        filename=file_storage.save(videofile.name,videofile)
        # video_path =file_storage.url(filename)
        video_path =os.path.join(file_storage.location,filename)
        if not os.path.exists(video_path):
            error_message = "Video file does not exist."
            return render(request, 'detection_error.html', {'error': error_message})
        
        cap= cv2.VideoCapture(video_path)
        import tensorflow as tf
        print("TensorFlow version:", tf.__version__)

        # Load the entire model (including architecture and weights)
        model = load_model('C:/Users/syamp/Desktop/Fog-Detection/keras_model.h5')  

        total_fog_percetage = []

        if not cap.isOpened():
            error_message="Error opening video file."
            return render(request,'detection_error.html',{'error':error_message})

        # Process each frame in the video
        while True:
            # Read a frame from the video
            ret, frame = cap.read()

            # Break the loop if the video has ended
            if not ret:
                break

                
            # Resize the frame to match the input shape of the model (224x224)
            resized_frame = cv2.resize(frame, (224, 224))

            # Normalize pixel values if necessary
            # ...

            # Make predictions using the loaded model
            fog_probability = model.predict(np.expand_dims(resized_frame, axis=0))[0, 0]


            # Set a threshold (adjust as needed)
            threshold = 0.5
            
           
            # Determine fog presence based on the threshold 
            if fog_probability > threshold:
        
                total_fog_percetage.append(fog_probability*100)
                percentage_text = f"Fog detection percentage: {fog_probability * 100:.2f}%"
                cv2.putText(frame, percentage_text, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)
                # Display fog detection message on the frame
                
                cv2.putText(frame, "Fog detected!", (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)
            else:
               
                no_fog_percentage = 0
                # Display no fog message on the frame
                cv2.putText(frame, "No fog detected", (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

             # Display the frame
            cv2.imshow('Video Frame', frame)


            # Exit the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        # Release the video capture and close any open windows
        cap.release()
        cv2.destroyAllWindows()
        
        # Calculate the average fog percentage with a check for ZeroDivisionError
        try:
            average_fog_percentage = sum(total_fog_percetage) / len(total_fog_percetage)

             #sent mail if fog percentage is more than 50%
            if  average_fog_percentage >= 50 :
                subject = 'Fog detection'
                mail_content =f'warning : fog detection percentage is {average_fog_percentage}'
                from_mail = 'fogdetectiontrial@gmail.com'
                recipient_list = ['traficunofficial@gmail.com']
                send_mail(subject, mail_content, from_mail, recipient_list)
                
                return render(request,'fog_percentage.html',{'f': average_fog_percentage })

        except ZeroDivisionError:
            print("Error: Division by zero. Unable to calculate the average.")

            return render(request,'fog_percentage.html',{'f':no_fog_percentage})
    else:
        return render(request,'home.html')
          

templates/detection_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>fog-detection-error</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <div class="container-fluid pt-5">

   

    <h2 class="text-center text-danger font-weight-bold">{{error}}</h2>
</div>
    
</body>
</html>

templates/fog_percentage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>fog-percentage</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body style="background-color: rgb(216, 216, 223);">
    <nav class="navbar-nav navbar-expand-lg navbar-light bg-danger p-4">
        <a class="navbar-brand" href="{% url 'fog_detection:home' %}" style="color: white;font-weight: bold;">FOG DETECTION</a>
      
        </nav>
    <div class="form-container pt-5">
      
        <h2 class="text-danger font-weight-bold text-center">{{f}}% of fog is detected.</h2>

    </div>
    
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>fog-detection</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <link rel="stylesheet" href="{% static 'home.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  </head>
<body style="background-color: rgb(216, 216, 223);">

  <nav class="navbar-nav navbar-expand-lg navbar-light bg-danger p-4">
  <a class="navbar-brand" href="{% url 'fog_detection:home' %}" style="color: white;font-weight: bold;">FOG DETECTION</a>

  </nav>

  <div class="pt-4">
  <h2 style="font-weight:bold ;" class="text-danger">DETECT FOG ON YOUR VIDEO </h2>
<div class="form-container">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="text-center">
  <input type="file" name="video_file">
 
  <input  type="submit" value="Upload and Detect Fog">
</div>

</form>
</div>
</div>


</body>
</html>